
services:
  course-service:
    build:
      context: ./CourseService/CourseService
      dockerfile: Dockerfile
    ports:
      - "7126:8080"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - EXCHANGE_RATE=${EXCHANGE_RATE}
      - CURRENCY_FREAKS=${CURRENCY_FREAKS}
      - OPEN_EXCHANGE_RATE=${OPEN_EXCHANGE_RATE}
    container_name: CourseServiceDev
  auth-service:
    build:
      context: ./AuthService/AuthService
      dockerfile: Dockerfile
    ports:
      - "7270:8080"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SECRET_KEY=${SECRET_KEY}
      - DB_CONNECTION_STRING=Server=${DB_HOST};Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD};
    container_name: AuthServiceDev
    depends_on:
      - database
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}         
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}           
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data: